# Generated by Django 4.2.7 on 2026-07-14 16:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_no', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DETECTED', '检测到灾害'), ('VERIFIED', '多源验证通过'), ('TRIGGERED', '理赔生成'), ('NOTIFIED', '已通知'), ('PAID', '已支付'), ('REJECTED', '已拒绝')], default='DETECTED', max_length=15)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('evidence_url', models.TextField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, help_text='External ID from APIs like NASA EONET', max_length=255, null=True, unique=True)),
                ('event_type', models.CharField(choices=[('FLOOD', 'Flood'), ('DROUGHT', 'Drought'), ('HEATWAVE', 'Heatwave'), ('WILDFIRE', 'Wildfire')], max_length=50)),
                ('affected_area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('severity_level', models.IntegerField(default=1, help_text='1: Low, 2: Medium, 3: High')),
                ('eo_metrics', models.JSONField(blank=True, default=dict, help_text="Store specific EO data (e.g. {'water_level_m': 3.2} or {'fire_area_ha': 12.5})")),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geofence', django.contrib.gis.db.models.fields.PolygonField(help_text='GNSS Geofencing boundaries (Polygon)', srid=4326)),
                ('crop_type', models.CharField(choices=[('maize', 'Maize (Corn)'), ('wheat', 'Wheat'), ('livestock', 'Livestock')], default='maize', max_length=50)),
                ('phone_number', models.CharField(help_text='用于接收短信预警', max_length=20)),
                ('wallet_address', models.CharField(blank=True, help_text='Web3 Wallet Address for payouts', max_length=42, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending SMS'), ('SENT', 'SMS Sent'), ('WARNING', 'Warning'), ('DISASTER', 'Disaster')], default='PENDING', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='置信度 0-100', max_digits=5)),
                ('ai_damage_report', models.TextField(blank=True, help_text='AI generated damage estimation report', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disasterevent')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.farm')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.claim')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.riskalert'),
        ),
        migrations.AddField(
            model_name='claim',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.farm'),
        ),
    ]
