# Generated by Django 4.2.30 on 2026-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert_unique_and_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('DETECTED', '检测到灾害'), ('VERIFIED', '多源验证通过'), ('TRIGGERED', '理赔生成'), ('NOTIFIED', '已通知'), ('PENDING', '待支付'), ('PAID', '已支付'), ('REJECTED', '已拒绝')], default='DETECTED', max_length=15),
        ),
    ]
