# Generated by Django 4.2.30 on 2026-09-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_normalize_claim_timeline_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimtimeline',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
